### ISSUE TITLE
Stable releases (Semantic Versioning)

### ISSUE THREAD

**Issue by VojtechVitek** [SparkPost/gosparkpost#111]
Hi,
can we start versioning this project and not break the API every few months?

This would be very useful for anyone using vendoring tools like [golang/dep](https://github.com/golang/dep), where you can upgrade to recent API-compatible version without breaking the builds.

I'd love to start using
```
[[constraint]]
  name = "github.com/SparkPost/gosparkpost"
  version = "^1.0.0"
```
rather than a specific commit SHA.

http://semver.org/

**Comment by yargevad** [comment]
Hi @VojtechVitek, I tagged [0.1.0](https://github.com/SparkPost/gosparkpost/releases/tag/0.1.0) just now. Not calling it version 1.0 just yet, since I haven't finished all that testing work quite yet.

**Comment by VojtechVitek** [comment]
Thanks @yargevad
