### ISSUE TITLE
Error while parsing response from SparkPost API

### ISSUE THREAD

**Issue by eluleci** [SparkPost/gosparkpost#114]
I am testing some cases where the emails are not valid. I used "a" as email and the SDK had error with message:

`parsing api response: json: cannot unmarshal number into Go struct field SPError.code of type string`

I think it's a bug in SparkPost API itself but I'm using this library so I wanted to describe it here.

**Comment by Teddy-Schmitz** [comment]
Hi we have also run into this issue, is there any workaround or fix?

**Comment by yepher** [comment]
When I try this usecase if I send to a single recipient `a` I see this error. I expect that is not the use case you are doing. Are you sending to multiple recipients?

In the multiple recipient case where one is invalid this is the response from the server:

```
{
    "errors": [
        {
            "message": "transmission created, but with validation errors",
            "description": "message submitted for generation successfully",
            "code": "2000"
        }
    ],
    "results": {
        "rcpt_to_errors": [
            {
                "message": "invalid data format/type",
                "description": "invalid recipient address.email: a",
                "code": "1300"
            }
        ],
        "total_rejected_recipients": 1,
        "total_accepted_recipients": 1,
        "id": "66633760885560781"
    }
}
```

For completeness this is the response with a single recipient which is bad:

```

**Comment by yepher** [comment]
Looking more closely at the outputs it looks like `errors ->code` is sometimes encoded as a string and other times it is encoded as an int. I will talk to our server team about this and report back.

**Comment by yepher** [comment]
Internal tracking ID: MO-6986

**Comment by Teddy-Schmitz** [comment]
We are always sending to a single recipient at this time, thanks for looking into this.

**Comment by Teddy-Schmitz** [comment]
Any update on this?

**Comment by yargevad** [comment]
We'll have to work around this inconsistency. I'll work on getting this out today or tomorrow.

**Comment by yargevad** [comment]
Not quite `today or tomorrow`, but the PR is up there, with tests showing that it handles the inconsistent input.
