### ISSUE TITLE
templates api: support all documented methods

### ISSUE THREAD

**Issue by yargevad** [SparkPost/gosparkpost#14]
https://www.sparkpost.com/api#/reference/templates/create-and-list/samples

**Comment by pxue** [comment]
Hey @yargevad 

I've started to expand the templates code with https://github.com/SparkPost/gosparkpost/pull/49 and I see other's have contributed as well (https://github.com/SparkPost/gosparkpost/pull/54). Is there a process we should follow to get these code merged upstream? Thanks!
