### ISSUE TITLE
Fix license to make docs work on pkg.go.dev

### ISSUE THREAD

**Issue by epelc** [SparkPost/gosparkpost#155]
Apparently pkg.go.dev doesn't show any docs for projects it can't detect a license for.

> If we are not able to detect one of the licenses below, only limited package and module information will be made available. If you are a package author seeking to make your content available on the Go website, please be aware that our detection algorithms can be affected by any modifications of the license text, or by the use of an uncommon license file name.
https://pkg.go.dev/license-policy

It looks like this project uses apache 2 which they support but it is not detected for some reason.

They say this:
>We currently use github.com/google/licensecheck for license detection, and look for licenses in files with the following names: COPYING, COPYING.md, COPYING.markdown, COPYING.txt, LICENCE, LICENCE.md, LICENCE.markdown, LICENCE.txt, LICENSE, LICENSE.md, LICENSE.markdown, LICENSE.txt, LICENSE-2.0.txt, LICENCE-2.0.txt, LICENSE-APACHE, LICENCE-APACHE, LICENSE-APACHE-2.0.txt, LICENCE-APACHE-2.0.txt, LICENSE-MIT, LICENCE-MIT, LICENSE.MIT, LICENCE.MIT, LICENSE.code, LICENCE.code, LICENSE.docs, LICENCE.docs, LICENSE.rst, LICENCE.rst, MIT-LICENSE, MIT-LICENCE, MIT-LICENSE.md, MIT-LICENCE.md, MIT-LICENSE.markdown, MIT-LICENCE.markdown, MIT-LICENSE.txt, MIT-LICENCE.txt, MIT_LICENSE, MIT_LICENCE, UNLICENSE, UNLICENCE. The match is case-insensitive.

Would be nice if it worked on pkg.go.dev as that is the replacement for godoc.org

**Comment by jba** [comment]
You are using a variant of the Apache 2.0 "header" form that we don't recognize. The text we use is in the box at the bottom of https://opensource.org/licenses/Apache-2.0.

Where is your alternative text from? It could be there is another canonical version of the text that we're not aware of, and we should recognize it.

**Comment by epelc** [comment]
Fixed from https://github.com/golang/go/issues/39388#issuecomment-761709172
