### ISSUE TITLE
Proposal: Please start using Semantic Versioning

### ISSUE THREAD

**Issue by KateGo520** [SparkPost/gosparkpost#158]
I found that this project already [supports Go modules](https://github.com/SparkPost/gosparkpost/blob/0.2.0/go.mod). But sadly, the [tags](https://github.com/SparkPost/gosparkpost/tags) doesn't follow [Semantic Versioning](https://semver.org), which means that all tags of this project will be ignored by Go modules and replaced by pseudo-versions, go get acts weirdly when tags are not in that form. It would be great to have the tagged release be named in the format vX.X.X format so that go mod can read it. 
```
$go get github.com/SparkPost/gosparkpost@0.2.0
go: downloading github.com/SparkPost/gosparkpost v0.0.0-20200518221114-5b781faf9f19
go: github.com/SparkPost/gosparkpost upgrade => v0.0.0-20200518221114-5b781faf9f19
```
Else the mod file shows something like `github.com/SparkPost/gosparkpost v0.0.0-20200518221114-5b781faf9f19` which is not very readable and difficult to upgrade. It’s hard to verify which version is in use. This is not conducive to version control.

So, I propose this project to follow Semantic Versioning in future versions. For example, `v1.0.1`, `v2.0.0`, `v3.1.0-alpha`, `v3.1.0-beta.2`etc, so that other project can use tag in go.mod.

**Comment by KateGo520** [comment]
@yargevad  @damianopetrungaro  Could you help me review this issue? Thx :p

**Comment by damianopetrungaro** [comment]
Hey @KateGo520 the "weird" thing you see after the 0.0.0 version is the commit hash, also I'd love to see this package versioned but I am not working at sparkpost, I'm pretty sure they have some people maintaining this.

For sure I'll be happy to review the changes, also,  those will be more related to the CI pipeline rather than pure go code and they may have company policy for that and not use GitHub Action

**Comment by yargevad** [comment]
Thanks for the report, this is unintentional. I'll see if I can quickly fix right now.

**Comment by yargevad** [comment]
Ok I copied the existing tags with a `v` prepended, so the `go get` command you showed above should work as expected now. Unfortunately the default looks like it still uses the auto-generated date/hash version:

    package main
    
    import (
    	"fmt"
    	gosp "github.com/SparkPost/gosparkpost"
    )
    
    func main() {
    	cfg := gosp.Config{}
    	fmt.Printf("%+v\n", cfg)
    }
    
    $ go build && grep gosparkpost go.sum
    github.com/SparkPost/gosparkpost v0.0.0-20200518221114-5b781faf9f19 h1:dnV8oALsRlQePwPuJkrMoDWA07cIpDjAVlNKNGtfZc0=
    github.com/SparkPost/gosparkpost v0.0.0-20200518221114-5b781faf9f19/go.mod h1:S9WKcGeou7cbPpx0kTIgo8Q69WZvUmVeVzbD+djalJ4=
    $ go get github.com/SparkPost/gosparkpost@v0.2.0 && grep gosparkpost go.sum
    go: downloading github.com/SparkPost/gosparkpost v0.2.0
    github.com/SparkPost/gosparkpost v0.0.0-20200518221114-5b781faf9f19 h1:dnV8oALsRlQePwPuJkrMoDWA07cIpDjAVlNKNGtfZc0=
    github.com/SparkPost/gosparkpost v0.0.0-20200518221114-5b781faf9f19/go.mod h1:S9WKcGeou7cbPpx0kTIgo8Q69WZvUmVeVzbD+djalJ4=
    github.com/SparkPost/gosparkpost v0.2.0 h1:yzhHQT7cE+rqzd5tANNC74j+2x3lrPznqPJrxC1yR8s=
    github.com/SparkPost/gosparkpost v0.2.0/go.mod h1:S9WKcGeou7cbPpx0kTIgo8Q69WZvUmVeVzbD+djalJ4=

Hope that makes things more intuitive.

**Comment by yargevad** [comment]
Oh and things worked fine after I manually removed the 2 `v0.0.0-20200518221114-5b781faf9f19` lines from `go.sum`

**Comment by KateGo520** [comment]
@yargevad @damianopetrungaro Thanks for your feedback.

**Comment by KateGo520** [comment]
Thank you for your contribution! It works now!
```
$go get github.com/SparkPost/gosparkpost
go: github.com/SparkPost/gosparkpost upgrade => v0.2.0
go: downloading github.com/SparkPost/gosparkpost v0.2.0
```

**Comment by KateGo520** [comment]
Close this issue, as it has been fixed.

Thanks again.
