### ISSUE TITLE
Timestamp is being decoded as `int64` instead of `string`

### ISSUE THREAD

**Issue by yepher** [SparkPost/gosparkpost#29]
events/events.go implementation is based on an error in SparkPost documentation. The `Timestamp` field is being decoded as `int64` instead of `String`.

**Comment by yepher** [comment]
Added a fix here:

Commit: 85d31e2e59fc74b00f66d6604a6c317896222149 [85d31e2]
Parents: fe82e99d2f
Author: Chris Wilson <github@yepher.com>
Date: February 11, 2016 at 9:23:22 AM CST
Labels: HEAD master

• Fixes problem where Timestamp was getting decoded as `int64` instead of `String`.
• Changes imports to be relative so it is easier to test local changes or changes on a branch.

**Comment by VojtechVitek** [comment]
https://github.com/SparkPost/gosparkpost/pull/35 parses timestamps into native golang `time.Time` values via custom JSON Unmarshaller. I noticed that Webhook Event API returns Unix timestamps (int64) and Event Samples API returns string of RFC 3339-like format.

Snippet:
```go
type Timestamp time.Time

func (t *Timestamp) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprint(time.Time(*t).Unix())), nil
}

func (t *Timestamp) UnmarshalJSON(data []byte) error {
	// Timestamps coming from Webhook Events are Unix timestamps.
	unix, err := strconv.ParseInt(string(data), 10, 64)
	if err == nil {
		*t = Timestamp(time.Unix(unix, 0))
		return nil
	}

	// Timestamps coming from Event Samples are in this RFC 3339-like format.
	customTime, err := time.Parse("\"2006-01-02T15:04:05.000-07:00\"", string(data))
	if err != nil {
		return err
	}

	*t = Timestamp(customTime)
	return nil
}
```

**Comment by VojtechVitek** [comment]
Seems like the API changed or something in the last few days -- and instead of pure Unix timestamp integers, the Webhook API now returns strings. I had to add another commit https://github.com/pressly/gosparkpost/commit/c848d16a4f77aec77fb6e89d5fffd94441632a1a to trim the quotes.

**Comment by VojtechVitek** [comment]
@yepher this can be closed, since Timestamps are now `time.Time` values
