### ISSUE TITLE
Sending Struct for SubstitutionData

### ISSUE THREAD

**Issue by timbutler** [SparkPost/gosparkpost#42]
**Disclaimer:** I'm very new to Go, so this could be a mistake / misunderstanding on my behalf.

I'm trying to send a struct type as the data for the SubstitutionData parameter in the Transmission struct but it fails at the AssertObject phase within the common.go file. This is because it doesn't match any of the accepted Types.

However, if I remove the limitation (and just have it return nil), this works as expected (since the struct has the JSON structure to Marshal from a struct to JSON).

Am I passing the data incorrectly, or is it a deficiency in the assertion?

Any suggestions would be appreciated.

**Comment by yargevad** [comment]
That would indeed be useful to be able to use a `struct` directly. Let me see what I can do to support that, or maybe remove the check for `SubstitutionData`. The trade off there would be that the client library then isn't able to protect you from sending unsupported types through, so there are more types of errors to handle.

**Comment by yargevad** [comment]
Hi @timbutler, this should be addressed with #62, thanks for the suggestion!

**Comment by timbutler** [comment]
Thanks for the heads up @yargevad, working perfectly!
