### ISSUE TITLE
Add the ability to accept a Template ID for the Transmission

### ISSUE THREAD

**Issue by timbutler** [SparkPost/gosparkpost#43]
Currently the Go Client is unable to use a template. This is because the Template ID is missing from the struct and the validation also needs to be adjusted. 

_This issue is a placeholder for the PR as per the contribution guidelines._

**Comment by yargevad** [comment]
`Transmissions.Content` is an `interface{}` and does allow using a stored template. although I guess it's not very clear how to do that. Here's an example, and check out `transmissions.go:ParseContent` for examples of supported types for `Content`.

```go
tx := &sparkpost.Transmission{
  Recipients: []string{"example@test.sink.sparkpostmail.com"},
  Content:    map[string]string{"template_id": "foo"},
}
err = tx.Validate()
if err != nil {
  log.Fatal(err)
}
```

Does that answer your question? If so, I'd like to convert this issue into a documentation task, to make it more clear which types are supported in `Transmissions.Content`.

**Comment by timbutler** [comment]
That makes sense, I could see the reference to template_id there but couldn't figure out how it worked. I'm new to Go sorry and used to doing things the "Pythonic" way :)

Happy for this to be closed, thanks for taking the time to give an example.

**Comment by vksci123** [comment]
@yargevad Hi Dave, Can I also pass campaign_id along with template_id in the map? Something as below

`  tx := &sp.Transmission{
    Recipients: emails,
    Content: map[string]string{
      "template_id": template_id,
      "compaign_id": campaign_id,                                                                                                                                       
    },  
  }`
