### ISSUE TITLE
Rename pkg name to sparkpost?

### ISSUE THREAD

**Issue by VojtechVitek** [SparkPost/gosparkpost#50]
``` go
import "github.com/SparkPost/gosparkpost"

func main() {
   var client sparkpost.Client
   // ....
}
```

**Comment by VojtechVitek** [comment]
I don't know any Golang pkg name with "go" prefix. If you guys are still willing to break the API, it'd be nice to rename the pkg.

**Comment by yargevad** [comment]
We have quite a few client libraries, and they all include the relevant language in the package name, so if we did change the import path, it would be to something like `github.com/SparkPost/go/sparkpost`, which would give you the same imported name.

Out of curiosity, what's preventing you from aliasing the package like so:

```go
import sparkpost "github.com/SparkPost/gosparkpost"
```

**Comment by VojtechVitek** [comment]
Yes, I can rename the pkg in the import path. All I'm saying is that go community doesn't usually have "go" prefix in the pkg names. So, the issue is rather:

1. Leave github.com/SparkPost/gosparkpost project name as is, it's fine
2. Rename `gosparkpost` pkg name to `sparkpost`, so:

```go
import "github.com/SparkPost/gosparkpost"

var client = sparkpost.Client
```

Leaving the pkg name `gosparkpost` is fine too. This was rather a naming suggestion before the project goes viral. Feel free to close if you prefer the gosparkpost pkg name.

**Comment by yargevad** [comment]
We're going to keep the name as-is, happy Saturday!
