### ISSUE TITLE
Document Client thread safety

### ISSUE THREAD

**Issue by dreadiscool** [SparkPost/gosparkpost#51]
Hello,

Are we supposed to create a new client per routine, or can the same client be re-used concurrently between multiple goroutines?

**Comment by yargevad** [comment]
The `Client` object is safe for concurrent read-only re-use, yes. You'll need to set up your `Config` and any non-default changes you need in the `http.Client` before going concurrent.

I'll rename this issue to make sure we get this info into the docs.

**Comment by yargevad** [comment]
Also document that all writes to `Client.headers` via `SetHeader` (see #58) must occur before the `Client` is exposed to possible concurrent use.
