### ISSUE TITLE
allow setting arbitrary headers on requests

### ISSUE THREAD

**Issue by yargevad** [SparkPost/gosparkpost#59]
In addition to having the `map[string]string` as a part of the `Client`, this will add `Headers *map[string]string` on the various objects that are encoded to JSON and passed to endpoints, like `Transmissions`.

The idea would be to build a `map[string]string` with your (for example) subaccount-specific details - even api key in the `Authorization` header if that's part of your use case), and reference that `map` to include those headers on requests using that object.

**Comment by kakysha** [comment]
Today I faced exactly the situation you warned about - a need to set different subaccounts (= client.Headers) from multiple goroutines. The solution with having separate set of headers for every api requests seems viable.

**Comment by yargevad** [comment]
I went a slightly different way with this in #80 - you can now pass in a `context.Context` with a `http.Header` key and a value of type (surprise, surprise) `http.Header`. Those headers will be applied the outgoing request for that call. `Context` headers are applied after `Client` headers, and both are now after the `Authorization` header is applied, so you may choose to override how API keys are sent, which could be particularly useful in combination with subaccounts.

When you take a look and/or try it out, let me know how it goes!
