### ISSUE TITLE
Transmission.Options.StartTime formatting Error

### ISSUE THREAD

**Issue by sarahyablok** [SparkPost/gosparkpost#61]
Tried sending an transmission like the following:

``` go
tx := &sp.Transmission {
    Recipients: []string{email},
    Content: map[string]string {
        "template_id": templateId,
    },
    Options: &sp.TxOptions {
        StartTime: time.Now().Add(time.Minute * 5),
    }
}
```
and `client.Send(tx)` returns the following error:

```json
{ "errors": [ { "message": "invalid data format\/type", "description": "Error parsing scheduled start_time", "code": "1300" } ] }
```

The docs seem to imply that the start_time should be RFC3339 formatted in the request body. Seems like this format should be applied before marshalling.

**Comment by yargevad** [comment]
Thanks for the report, this is fixed with #63
