### ISSUE TITLE
Remove HTTPS rqmt

### ISSUE THREAD

**Issue by yepher** [SparkPost/gosparkpost#92]
The requirement for HTTPS should be removed so this library can be used with HTTP on Momentum instances too.

https://github.com/SparkPost/gosparkpost/blob/master/common.go#L95

**Comment by yargevad** [comment]
There actually isn't a hard `https` requirement - you're free to either not call `Client.Init()`, or to modify the `Client.Config.BaseUrl` value yourself after calling `Client.Init()`.

**Comment by yepher** [comment]
This is perfect thank you.
